---
title: "Resume"
output: html_document
---


Connor Goldman 

cg3112@cumc.columbia.edu  
PHONE: 404-829-5167 

# EDUCATION: 

##### Columbia University Mailman School of Public Health New York, NY ______________________    Anticipated May 2020 

Master of Public Health, Department: Epidemiology, Certificate: Infectious Disease 

 

##### Vanderbilt University, Nashville, TN    _______________________________________________    May 2018 

Bachelor of Arts, Major: Biological Sciences Minor: Spanish 

•    Worked up to 25 hours per week while attending school full-time 

 

# RELEVANT EXPERIENCE: 

##### Research/Admin. Assistant, NewYork-Presbyterian Hospital, New York, NY  _______________   March 2019 – Present 
•    Help draft and prepare research and grant proposals 

•    Design epidemiological research studies including observational cohort and case control studies   

•    Organize meeting and travel schedule of Dr. Lisa Saiman 

•    Utilize SAS, Excel, and Python to analyze epidemiological data 

•    Maintain relationship databases for studies using Microsoft Access 

 

##### Research Assistant, Vanderbilt Institute of Imaging Science, Nashville, TN _____________ Sept 2016 –  May 2018  

•    Conducted analysis of data using PRISM software and mapped images to models 

•    Reviewed relevant scientific literature in the field of mGluR2 drug discovery for schizophrenia treatment   

•    Researched drug mechanism of mGluR2 potentiators: utilized functional MRI scans (cerebral blood volume and BOLD techniques) to analyze the regions engaged by amphetamine and mGluR2 potentiators in rats; accurately followed research protocols to ensure accuracy 

•    Worked in the laboratory of Dr. Nellie Byun, Assistant Professor 

 

##### Radiologic Technical Assistant, Wellstar Kennestone Hospital, Kennesaw, GA ___________ July 2016 – August 2016 

•    Provided high quality patient care and assisted in transporting X-ray patients for procedures 

•    Helped to take X-Rays with bedside mobile units   

   

##### Public Health Intern, Mayor Potencial, El Rodeíto, Honduras ___________________________ June 2015 – July 2015 

•     Designed a comprehensive curriculum for Math, Science, and English for 2nd graders based off of Honduran education standards 

•     Shadowed the town’s only nurse managing the medical problems of the entire town of about 400  

•     Assessed the efficacy of the clinic formulary by reviewing available vaccinations and prescriptions 

•     Gathered medical data from local K – 6th graders as well as many infants in surrounding towns 

•     Travelled to Cornell University to present findings 

 

# PUBLICATIONS: 

##### LeCompte, Michael. **Goldman, Connor**. 2017 “Incorporation of a Global Surgery Rotation into an Academic General Surgery Residency.” 

 •     Determining effects of international surgery rotation on global health orientation 

 •     Gathered survey data and helped to write publication 

 

# VOLUNTEER ACTIVITES/LEADERSHIP: 

##### Timmy Global Health, Executive Cabinet/Public Relations Chair _____________________   November 2016 – May 2018 

•    Served on Executive Cabinet, Public Relations Chair overseeing use of social media for advertisement 

•    Helped organize a fundraising event for international health care 

 

##### Vanderbilt Student Volunteers for Science, Team Leader _______________________________ January 2015 – May 2018 

•     Travelled once a week to teach middle school students science lessons 

•     Team leader, responsible for communication of lesson plans to a group of volunteers 

 

##### Camp Kesem, Camp Counselor __________________________________________________________ March 2017 – May 2018 

•    Trained on managing a camp for 8-16-year-olds with parents affected by cancer 

•    Served as a camp counselor for 9 and 10-year-old campers 

•    Helped to fundraise to send 1 child to camp for free 

 

##### Remote Area Medical, Spanish Translator _________________________________________________________   March 2018 

•    Translated for non-English speakers in a large pop-up clinic in Cookeville, Tennessee 

•    Collaborated with nurses, dentists, and optometrists to ensure care 

 

##### Pi Kappa Alpha Fraternity, Executive Cabinet ____________________________________________ August 2015 – present  

•     Served as Executive Cabinet, Scholarship Chair overseeing academic achievement of members 

 

##### Etowah High School, Class President, Woodstock, GA __________________________________________________ May, 2014 


# SKILLS: 

Software- SAS (Spring 2019), Microsoft Office, GraphPrism, R Studio, Familiar with STATA 

Languages- Spanish (proficient) 

Others- Collaboration, Team-Building, Laboratory Work, Basic Sciences 

 

# WORK EXPERIENCE: 

##### MAFIAoZA’s Pizzeria & Neighborhood Pub, Server, Nashville, TN __________________________ June 2017 – May 2018  

##### Ben & Jerry’s Ice Cream, Store Clerk, Nashville, TN _________________________________ March 2015 – October 2016 
##### Johnny’s Pizza, Busboy/ Cook/ Server, Woodstock, GA ______________________________________ May 2013 – July 2014 

•    Provided high-quality customer service in a fast-paced environment and handled up to $300 per day 

•    At Ben & Jerry’s, promoted to shift leader after 6 months and learned advanced management functions; trained new employees; responsible for managing up to $600 in transactions per day 

 

##### ReVision, Start-Up Founder Woodstock, GA ____________________________________________  June 2016 – August 2016 

•    Launched a college application guidance company with two other colleagues called “ReVision” 

•    Met with local high school principals to promote guidance service to students applying to college 

•    Helped to design a website and other advertisements for the company 

•    Determined pricing and template consultation script 

   

# ACTIVITIES: 

•     Vanderbilt Club Crew Team (Fall 2014) 

•     Relay for Life (Spring 2015) 




